---
apiVersion: v1
kind: Service
metadata:
  name: www-yorqat-service
spec:
  selector:
    app: www-yorqat
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-yorqat-tls-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: www.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: www-yorqat-service
                port:
                  number: 80
  tls:
    - secretName: www-yorqat-tls
      hosts:
        - www.$DOMAIN_NAME
